"""pgvector embedding + full-text search for retrieval

Revision ID: 0003
Revises: 0002

Switches chunks.embedding from JSONB to a pgvector column with an HNSW index and
adds a generated tsvector column with a GIN index for keyword search. Existing
chunks are truncated because the embedding representation changes; they are
regenerated by re-running ingestion (content is retained in document_contents).
"""
from alembic import op

revision = "0003"
down_revision = "0002"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("TRUNCATE TABLE chunks")
    op.execute("ALTER TABLE chunks DROP COLUMN embedding")
    op.execute("ALTER TABLE chunks ADD COLUMN embedding vector(384) NOT NULL")
    op.execute(
        "ALTER TABLE chunks ADD COLUMN text_tsv tsvector "
        "GENERATED ALWAYS AS (to_tsvector('english', text)) STORED"
    )
    op.execute(
        "CREATE INDEX ix_chunks_embedding_hnsw ON chunks "
        "USING hnsw (embedding vector_cosine_ops)"
    )
    op.execute("CREATE INDEX ix_chunks_text_tsv ON chunks USING gin (text_tsv)")


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_chunks_text_tsv")
    op.execute("DROP INDEX IF EXISTS ix_chunks_embedding_hnsw")
    op.execute("ALTER TABLE chunks DROP COLUMN IF EXISTS text_tsv")
    op.execute("ALTER TABLE chunks DROP COLUMN embedding")
    op.execute("ALTER TABLE chunks ADD COLUMN embedding jsonb NOT NULL")
