apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eka.fullname" . }}-secret
  labels:
    {{- include "eka.labels" . | nindent 4 }}
type: Opaque
stringData:
  EKA_DATABASE_DSN: {{ include "eka.databaseDsn" . | quote }}
  EKA_JWT_SECRET: {{ include "eka.jwtSecret" . | quote }}
  {{- if .Values.postgresql.enabled }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password | quote }}
  {{- end }}
